name: Packer Image Deployment

on:
    workflow_dispatch: 

jobs:
    packer_image_deployment:
        runs-on: ubuntu-latest
        environment: development

        steps:

            - name: Checkout to the Repository
              uses: actions/checkout@v2

            - name: Install Packer
              run: |
                wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
                echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
                sudo apt update && sudo apt install packer

            # - name: Install AWS-CLI
            #   run: |
            #     curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            #     unzip awscliv2.zip
            #     sudo ./aws/install
            #     ./aws/install -i /usr/local/aws-cli -b /usr/local/bin
            #     aws --version

            - name: AWS Login
              uses: aws-actions/configure-aws-credentials@v1
              env: 
                ACCESS_KEY: ${{secrets.ACCESS_KEY}}
                SECRET_ACCESS_KEY: ${{secrets.SECRET_ACCESS_KEY}}
              with: 
                aws-access-key-id: ${{secrets.ACCESS_KEY}}
                aws-secret-access-key: ${{secrets.SECRET_ACCESS_KEY}}
                aws-region: ${{secrets.AWS_REGION}}
                
            - name: Initialise Packer Plugins
              run: |
                packer init .
            
            - name: Format Packer File
              run: |
                packer fmt .

            - name: Validate Packer File
              run: |
                packer validate .

            - name: Build Packer Image
              run: |
                packer build aws-ubuntu.pkr.hcl
